version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/inframonitor"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "docker"
    directory: "/grafana"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "pymongo"
    open-pull-requests-limit: 1
  - package-ecosystem: "pip"
    directory: "/inframonitor/common"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "pymongo"
