version: '3.5'
# Production overrides
# This file is read by docker-compose by default if no docker-compose file is specified
services:
  nginx:
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/certs:/etc/ssl/private:ro

  mqtt:
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /srv/certs:/certs:ro

  influxdb:
    restart: unless-stopped
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /srv/certs:/etc/ssl:ro

  mongodb:
    restart: unless-stopped
    command: --auth

  grafana:
    restart: unless-stopped
    env_file: [ /srv/grafana/secret.env ]

  admin:
    restart: unless-stopped
    env_file: [ /srv/admin/secret.env, /srv/inframonitor_common/secret.env ]

  mqttagent:
    restart: unless-stopped
    env_file: [ /srv/inframonitor_common/secret.env ]

  httpagent:
    restart: unless-stopped
    env_file: [ /srv/inframonitor_common/secret.env ]

  mongoagent:
    restart: unless-stopped
    env_file: [ /srv/inframonitor_common/secret.env ]

  prediction:
    restart: unless-stopped
    env_file: [ /srv/inframonitor_common/secret.env ]

  reset:
    restart: unless-stopped
    env_file: [ /srv/inframonitor_common/secret.env ]

  monitor:
    restart: unless-stopped
    env_file: [ /srv/inframonitor_common/secret.env ]

  alert:
    restart: unless-stopped
    env_file: [ /srv/inframonitor_common/secret.env, /srv/alert/secret.env ]

  mongodb-proxy:
    restart: unless-stopped

  api:
    restart: unless-stopped
    env_file: [ /srv/inframonitor_common/secret.env, /srv/api/secret.env ]


