FROM python:3.12.0a7-slim

WORKDIR /app
RUN pip install --upgrade pip
COPY common/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY admin/requirements.txt /tmp/requirements-admin.txt
RUN pip install -r /tmp/requirements-admin.txt

COPY /common ./common
COPY /admin ./admin
HEALTHCHECK CMD python -c "import requests; requests.get('http://localhost')" || exit 1
CMD ["/app/admin/run.sh"]
