server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: journal
  journal:
    labels:
      job: journal
  relabel_configs:
  - source_labels: ['__journal__hostname']
    target_label: host
  - source_labels: ['__journal_priority_keyword']
    target_label: level
  - source_labels: ['__journal__systemd_unit']
    target_label: systemd_unit
  - source_labels: ['__journal_syslog_identifier']
    target_label: syslog_identifier
  - source_labels: ['__journal_container_name']
    target_label: container_name
